### ISSUE TITLE
Nova tasca

### ISSUE THREAD

**Issue by isidrocuma** [isidrocuma/Fraidei_isidro#2]
Bones,

crea una segona branca anomenada "col_divendres" i a dins un document "bondia.txt" amb la data d'avui.

**Comment by MiquelBasart-UdG** [comment]
No havia vist el comentari:

Bones,

crea una segona branca anomenada "col_divendres" i a dins un document "bondia.txt" amb la data d'avui.

He creat una branca issue2Miquel i he creat el fitxer Miquel.txt

**Comment by isidrocuma** [comment]
Cap problema, ho donem com a bona la tasca ;)

**Comment by MiquelBasart-UdG** [comment]
T’he fet una pull requests de la issue #2
